name: sde_harness
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - pandas>=1.3.0
  
  # PyTorch ecosystem
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - transformers>=4.30.0
  
  # Development tools
  - pip
  - jupyter
  - ipython
  
  # Data handling
  - pyyaml
  - requests
  - aiohttp
  
  # Optional visualization
  - matplotlib>=3.5.0
  - seaborn
  
  # Testing and development
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  
  # Pip dependencies (not available in conda)
  - pip:
    # Core framework dependencies
    - litellm>=1.73.6
    - weave>=0.51.54
    - asyncio-throttle>=1.0.0
    - tenacity>=8.0.0
    
    # LLM providers
    - openai>=1.0.0
    - google-generativeai>=0.3.0
    - anthropic>=0.25.0
    
    # Additional utilities
    - rich  # For better CLI output
    - click  # Alternative CLI framework
    - tqdm   # Progress bars
    
    # Install the framework in development mode
    - -e .