

PROMPT_G = (
    "I have a pool of 50 ligands in a csv file format below.\n"
    + "{CSV_FILE_CONTENT}"
    + "\n"
    + "This csv files contains the SMILES string, id, charge, and the connecting atoms and index (corresponding to the occurrance of the connecting element) that coordiate to the metal of each ligand.\n"
    + "You will use this pool of ligands frequently. Please remember the correspondence between their SMILES string, id, charge, and connecting atom element.\n"
    + "\n"
    + "I am interested in making a Pd based square planer transition metal complex (TMC) with Pd in +2 oxidation state.\n"
    + "My design objective is to maximize its HOMO-LUMO gap while making the total charge of the TMC to be -1, 0 or 1.\n"
    + "All ligands in the TMC need to be those present in this csv file.\n"
    + "I have made {NUM_PROVIDED_SAMPLES} TMCs and measured their total charge and HOMO-LUMO gap.\n"
    + "There might be a lot of data points for TMCs being provided. Please pay attention most to TMCs those that can achieve my design objective.\n"
    + "They are provided in a format of TMC, total charge, HOMO-LUMO gap.\n"
    + "The $TMC should be in a format of Pd_$L1_$L2_$L3_$L4, where Pd is the metal center , $L1, $L2, $L3, and $L4 are the id of the ligands (listed in the csv file) and follow a clockwise ordering.\n"
    + "Note that the $TMC has cyclic symmetry for the ligands so that Pd_$L1_$L2_$L3_$L4, Pd_$L2_$L3_$L4_$L1, Pd_$L3_$L4_$L1_$L2, and Pd_$L4_$L1_$L2_$L3 are the same TMC.\n"
    + "Below are the TMCs and their ground-truth total charge and HOMO-LUMO gap.\n"
    + "{CURRENT_SAMPLES}"
    + "\n"
    + "Grounded on your chemistry knowledge, look at the pattern of the provided data and think about what makes a TMC with large HOMO-LUMO gap.\n"
    + "Then please propose {NUM_SAMPLES} *NEW* TMCs that have HOMO-LUMO gap larger than all the TMCs above.\n"
    + "You can make ligand crossover (i.e., swap ligands in the TMCs) and ligand mutations (i.e., substitude ligands in TMCs with thr 50 ligands in the pool) based on your knowledge to achieve the design objective.\n"
    + "If you want to be creative, you can also propose new TMCs by taking advantage of your chemistry knowledge to achieve the design objective.\n"
    + "You should make use of BOTH the ground-truth HOMO-LUMO gap data for the TMCs provided above AND your chemistry knowledge.\n"
    + "But be aware that your chemistry knowledge may be challenged in this task. When this happens, please treat the data provided as the ground truth.\n"
    + "Also please DO NOT get stuck with the existing TMCs and ligands and try to be exploratory.\n"
    + "Be sure to use the id of provided pool of 50 ligands and control the total charge of the TMC to be -1, 0, or 1, otherwise the TMC would be considered as invalid. T\n"
    + "In addition, please DO NOT propose duplicated TMCs that I have listed above.\n"
    + "\n"
    + "Your output should follow the format: <<<Explaination>>>: $EXPLANATION, <<<TMC>>>: [$TMC],  <<<TOTAL_CHARGE>>>: $total charge, <<<gap>>>: $GAP. Here are the requirements that you should fulfill:\n"
    + "1. $EXPLANATION should be your analysis about why the new TMC would have a larger HOMO-LUMO gap.\n"
    + "2. The $TMC should be in a format of Pd_$L1_$L2_$L3_$L4, where Pd is the center metal. $L1, $L2, $L3, and $L4 should be the id of the ligands (listed in the csv file) and follow a clockwise ordering. Please give all TMCs in a list."
    + "3. The $TMC should be valid with a total charge of -1, 0 or 1.\n"
    + "4. The $TMC should not be a duplicate of the TMCs that have been provided. If the $TMC is a duplicate, please come up with a new one instead.\n"
    + "5. $GAP is your prediction of the HOMO-LUMO gap for $TMC based on your chemistry knowledge and provided data.\n"
)


PROMPT_MB = (
    "I have a pool of 50 ligands in a csv file format below.\n"
    + "{CSV_FILE_CONTENT}"
    + "\n"
    + "This csv files contains the SMILES string, id, charge, and the connecting atoms and index (corresponding to the occurrance of the connecting element) that coordiate to the metal of each ligand.\n"
    + "You will use this pool of ligands frequently. Please remember the correspondence between their SMILES string, id, charge, and connecting atom element.\n"
    + "\n"
    + "I am interested in making a Pd based square planer transition metal complex (TMC) with Pd in +2 oxidation state.\n"
    + "My design objective is to find TMCs that simultaneously maximize both HOMO-LUMO gap (> 4 eV) and polarisability (> 400 au), potentially by maximizing their mutiplication, while making the total charge of the TMC to be -1, 0 or 1.\n"
    + "At least give me TMCs with HOMO-LUMO gap > 4 eV and polarisability > 400 au. All ligands in the TMC need to be those present in this csv file.\n"
    + "I have made {NUM_PROVIDED_SAMPLES} TMCs and measured their total charge, HOMO-LUMO gap, and polarisability.\n"
    + "There might be a lot of data points for TMCs being provided. Please pay attention most to TMCs those that can achieve my design objective.\n"
    + "They are provided in a format of $TMC, $total charge, $HOMO-LUMO gap, $polarisability.\n"
    + "The $TMC should be in a format of Pd_$L1_$L2_$L3_$L4, where Pd is the metal center , $L1, $L2, $L3, and $L4 are the id of the ligands (listed in the csv file) and follow a clockwise ordering.\n"
    + "Note that the $TMC has cyclic symmetry for the ligands so that Pd_$L1_$L2_$L3_$L4, Pd_$L2_$L3_$L4_$L1, Pd_$L3_$L4_$L1_$L2, and Pd_$L4_$L1_$L2_$L3 are the same TMC.\n"
    + "Below are the TMCs and their ground-truth total charge, HOMO-LUMO gap, and polarisability.\n"
    + "{CURRENT_SAMPLES}"
    + "\n"
    + "Grounded on your chemistry knowledge, look at the pattern of the provided data and think about what makes a TMC have both extremely large HOMO-LUMO gap and polarisability.\n"
    + "Then please propose {NUM_SAMPLES} *NEW* TMCs that further maximize these two properties at the same time, potentially by maximizing their mutiplication.\n"
    + "If you find the TMCs listed above have extremely large polarisability (> 450 au) but small HOMO-LUMO gap (< 2 eV), propose more TMCs with larger HOMO-LUMO gap while maintaining their polarisability.\n"
    + "In contrast, if you find the TMCs have extremely small polarisability (< 250 au) but large HOMO-LUMO gap (> 4.5 eV), propose more TMCs with larger polarisability while maintaining their HOMO-LUMO gap.\n"
    + "You can make ligand crossover (i.e., swap ligands in the TMCs) and ligand mutations (i.e., substitude ligands in TMCs with thr 50 ligands in the pool) based on your knowledge to achieve the design objective.\n"
    + "If you want to be creative, you can also propose new TMCs by taking advantage of your chemistry knowledge to achieve the design objective.\n"
    + "You should make use of BOTH the ground-truth HOMO-LUMO gap and polarisability data for the TMCs provided above AND your chemistry knowledge.\n"
    + "But be aware that your chemistry knowledge may be challenged in this task. When this happens, please treat the data provided as the ground truth.\n"
    + "Also please DO NOT get stuck with the existing TMCs and ligands and try to be exploratory.\n"
    + "Be sure to use the id of provided pool of 50 ligands and control the total charge of the TMC to be -1, 0, or 1, otherwise the TMC would be considered as invalid. T\n"
    + "In addition, please DO NOT propose duplicated TMCs that I have listed above.\n"
    + "\n"
    + "Your output should follow the format: <<<Explaination>>>: $EXPLANATION, <<<TMC>>>: [$TMC],  <<<TOTAL_CHARGE>>>: $total charge, <<<gap>>>: $GAP, <<<polarisability>>>: $polarisability. Here are the requirements that you should fulfill:\n"
    + "1. $EXPLANATION should be your analysis grounded on chemistry knowledge and provided data about why the new TMC would have extremely large HOMO-LUMO gap and polarisability.\n"
    + "2. The $TMC should be in a format of Pd_$L1_$L2_$L3_$L4, where Pd is the center metal. $L1, $L2, $L3, and $L4 should be the id of the ligands (listed in the csv file) and follow a clockwise ordering. Please give all TMCs in a list.\n"
    + "3. The $TMC should be valid with a total charge of -1, 0 or 1.\n"
    + "4. The $TMC should not be a duplicate of the TMCs that have been provided. If the $TMC is a duplicate, please come up with a new one instead.\n"
    + "5. $GAP is your prediction of the HOMO-LUMO gap for $TMC based on your chemistry knowledge and provided data.\n"
    + "6. $polarisability is your prediction of the polarisability for $TMC based on your chemistry knowledge and provided data.\n"
)

