# LLMSR Configuration File

# Default model settings
model:
  name: "openai/gpt-4o-2024-08-06"
  max_tokens: 1000
  temperature: 0.1

# Workflow settings
workflow:
  max_iterations: 5
  max_params: 10
  optimization_method: "BFGS"

# Dataset settings
dataset:
  default: "lsrtransform"
  available_datasets:
    - "lsrtransform"
    - "bio_pop_growth"
    - "chem_react"
    - "matsci"
    - "phys_osc"

# Evaluation settings
evaluation:
  metrics:
    - "nmse"
    - "rmse"
    - "mae"
    - "improvement_rate"
    - "convergence_score"
  
  # Parameter optimization settings
  optimization:
    max_iter: 1000
    tolerance: 1e-6

# Output settings
output:
  default_dir: "outputs"
  save_intermediate: true
  save_equations: true
  save_plots: false

# Logging settings
logging:
  level: "INFO"
  save_logs: true
  log_dir: "logs"

